### ISSUE TITLE
How about less restrictive license?

### ISSUE THREAD

**Issue by tehKaiN** [Cons-Cat/libCat#2]
Hi,

I'm considering development of my next Commodore Amiga game using C++, but unfortunately the prominent distribution of bleeding edge GCC in our community lacks STL and most of stdlib. So, I'm looking for a replacement, and this one looks like it could do the job! If it works with reasonable performance, which I think it will, I'd probably end up endorsing this library to be used in tandem with my Amiga gamedev library/framework, which I'm developing for 10 years now.

Unfortunately, linking with GPL (or Affero GPL) requires making the remaining code on similar license, which is kinda no no for me - I'm all for open source, but forcing such license discourages some commercial scenarios, unfortunately - speaking plainly, you can't keep your game closed source while using open code, which is something some of my users prefer doing.

So, how about using some lightweight, less viral license with less text and caveats? If you want people to share their modifications back, MPL2 could be a good choice. If you just prefer attribution, MIT/BSD would be just fine. Or is it GPL because your code borrowed something GPLy from other source?

Thanks for considering it!

**Comment by Cons-Cat** [comment]
I was actually planning on switching to Mozilla Public License. What do you think about that one? Btw, I wouldn't recommend using libCat for anything in the near future as it is lacking many important features.

**Comment by tehKaiN** [comment]
I'm using MPL2 for my library/framework, so that's perfect!

I'll be fooling around this next year though, since I have to wrap up my current project first. From what I see libCat has vector, array and optional, and that's what I need the most, and there are also some other goodies on top of it. Other stuff can be added later, and perhaps even contributed in some PRs, I guess. ;)

**Comment by Cons-Cat** [comment]
This repository now uses MPL 2.0. Sorry that I took so long to get on this!

**Comment by tehKaiN** [comment]
Great stuff! Will try to use this soon-ish and give you a bit of feedback. ;)
